# -*- coding: utf-8 -*-
"""FCFS Disk Scheduling Algorithm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XQmJSfkgSBQ-w3qsBaxsMOFAgk3nQgpc
"""

def seek_calc(req, head, i=0, total=0):
    if i == len(req):
        return total
    return seek_calc(req, req[i], i+1, total + abs(req[i] - head))

# Taking input
n = int(input("Enter number of requests: "))
req = list(map(int, input("Enter request sequence: ").split()))
head = int(input("Enter initial head position: "))

total_seek = seek_calc(req, head)
print("Total seek operations:", total_seek)